security:
  oauth2:
    client:
      clientId: replace-with-your-client-id
      clientSecret: replace-with-your-client-secret
      scope: email, user_likes
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me?fields=id,name,email,likes